### ISSUE TITLE
RedisSink does not work with Jet 4.1.1

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet-contrib#83]
```
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.hazelcast.jet.impl.util.Util.checkSerializable(java.lang.Object, java.lang.String)'
	at com.hazelcast.jet.contrib.redis.RedisSinks.hash(RedisSinks.java:141)
	at com.hazelcast.jet.examples.callhomes.CountDistinctVersionsHomes.main(CountDistinctVersionsHomes.java:51)
```

**Comment by jerrinot** [comment]
It was caused by this change: https://github.com/hazelcast/hazelcast-jet/commit/cc3a51ad4e2ff5fbc8499979a91d1d94edb4ee75#diff-0309b636066cb39dd2e80cf494db06e3R171 which is not binary compatible (a different return type)

It's hard to blame this commit though as it's an internal class.

**Comment by viliam-durina** [comment]
Contributed sinks should not use private API...
