### ISSUE TITLE
hazelcast-jet-spring-boot-starter fails to compile for Spring Boot 2.4.0

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet-contrib#99]
Works on Spring Boot `2.3.6.RELEASE` but not with newer `2.4.0`

Gives
```
hazelcast-jet-contrib/hazelcast-jet-spring-boot-starter/src/main/java/com/hazelcast/jet/contrib/actuate/autoconfigure/HazelcastJetHealthIndicatorAutoConfiguration.java:22: error: cannot find symbol
import org.springframework.boot.actuate.autoconfigure.health.CompositeHealthIndicatorConfiguration;
                                                            ^
  symbol:   class CompositeHealthIndicatorConfiguration
  location: package org.springframework.boot.actuate.autoconfigure.health
```
